services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dunning-dashboard
    restart: unless-stopped
    networks:
      - apps-network

networks:
  apps-network:
    external: true
