services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dunning-dashboard
    restart: unless-stopped
    networks:
      - internal-net

networks:
  internal-net:
    external: true
